import { getRequiredElement } from "./utils/dom";

export const domRefs = {
  fileInput: getRequiredElement<HTMLInputElement>("#file"),
  uploadStatus: getRequiredElement<HTMLElement>("#uploadStatus"),
  standardizeStatus: getRequiredElement<HTMLElement>("#standardizeStatus"),
  authGate: getRequiredElement<HTMLElement>("#authGate"),
  authCodeInput: getRequiredElement<HTMLInputElement>("#authCodeInput"),
  authLoginButton: getRequiredElement<HTMLButtonElement>("#authLoginButton"),
  authStatus: getRequiredElement<HTMLElement>("#authStatus"),

  stateMigrationBanner: getRequiredElement<HTMLElement>("#stateMigrationBanner"),
  stateMigrationList: getRequiredElement<HTMLUListElement>("#stateMigrationList"),
  globalWarningPanel: getRequiredElement<HTMLElement>("#globalWarningPanel"),
  globalWarningList: getRequiredElement<HTMLUListElement>("#globalWarningList"),
  adminModeToggle: document.querySelector<HTMLInputElement>("#adminModeToggle"),

  drawerBackdrop: getRequiredElement<HTMLElement>("#drawerBackdrop"),
  notificationDrawer: getRequiredElement<HTMLElement>("#notificationDrawer"),
  instructorDrawer: getRequiredElement<HTMLElement>("#instructorDrawer"),
  headerRuntimePanel: getRequiredElement<HTMLElement>(".header-runtime-panel"),
  headerCurrentTime: getRequiredElement<HTMLElement>("#headerCurrentTime"),
  headerSyncState: getRequiredElement<HTMLElement>("#headerSyncState"),
  openNotificationDrawerButton: getRequiredElement<HTMLButtonElement>("#openNotificationDrawer"),
  openInstructorDrawerButton: getRequiredElement<HTMLButtonElement>("#openInstructorDrawer"),
  quickNavCourseButton: getRequiredElement<HTMLButtonElement>("#quickNavCourse"),
  quickNavSubjectButton: getRequiredElement<HTMLButtonElement>("#quickNavSubject"),
  quickNavInstructorButton: getRequiredElement<HTMLButtonElement>("#quickNavInstructor"),
  quickNavMappingButton: getRequiredElement<HTMLButtonElement>("#quickNavMapping"),
  quickNavCourseMeta: getRequiredElement<HTMLElement>("#quickNavCourseMeta"),
  quickNavSubjectMeta: getRequiredElement<HTMLElement>("#quickNavSubjectMeta"),
  quickNavInstructorMeta: getRequiredElement<HTMLElement>("#quickNavInstructorMeta"),
  quickNavMappingMeta: getRequiredElement<HTMLElement>("#quickNavMappingMeta"),
  jibbleRightMemberText: document.querySelector<HTMLElement>("#jibbleRightMemberText"),
  jibbleRightStatInstructor: document.querySelector<HTMLElement>("#jibbleRightStatInstructor"),
  jibbleRightStatCohort: document.querySelector<HTMLElement>("#jibbleRightStatCohort"),
  jibbleRightStatConflict: document.querySelector<HTMLElement>("#jibbleRightStatConflict"),
  jibbleOpsStatus: document.querySelector<HTMLElement>("#jibbleOpsStatus"),
  jibbleOpsSummary: document.querySelector<HTMLElement>("#jibbleOpsSummary"),
  jibbleManagementSubmenu: document.querySelector<HTMLElement>("#jibbleManagementSubmenu"),
  jibbleSubCourseButton: document.querySelector<HTMLButtonElement>("#jibbleSubCourse"),
  jibbleSubSubjectButton: document.querySelector<HTMLButtonElement>("#jibbleSubSubject"),
  jibbleSubInstructorButton: document.querySelector<HTMLButtonElement>("#jibbleSubInstructor"),
  jibbleMainNav: document.querySelector<HTMLElement>("#jibbleMainNav"),
  jibblePrimaryNavButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>("#jibbleMainNav .jibble-nav-item[data-nav-key]"),
  ),
  jibbleSubNavButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".jibble-nav-sub .jibble-nav-item[data-scroll-target]"),
  ),
  jibblePageGroupElements: Array.from(document.querySelectorAll<HTMLElement>("[data-page-group]")),
  menuConfigList: getRequiredElement<HTMLElement>("#menuConfigList"),
  saveMenuConfigButton: getRequiredElement<HTMLButtonElement>("#saveMenuConfigButton"),
  resetMenuConfigButton: getRequiredElement<HTMLButtonElement>("#resetMenuConfigButton"),
  menuConfigStatus: getRequiredElement<HTMLElement>("#menuConfigStatus"),
  openConflictDetailModalButton: getRequiredElement<HTMLButtonElement>("#openConflictDetailModal"),
  conflictDetailModal: getRequiredElement<HTMLDialogElement>("#conflictDetailModal"),
  conflictDetailTitle: getRequiredElement<HTMLElement>("#conflictDetailTitle"),
  conflictDetailContent: getRequiredElement<HTMLElement>("#conflictDetailContent"),
  closeConflictDetailModalButton: getRequiredElement<HTMLButtonElement>("#closeConflictDetailModal"),

  riskCardTime: getRequiredElement<HTMLElement>("#riskCardTime"),
  riskTimeConflict: getRequiredElement<HTMLElement>("#riskTimeConflict"),
  riskCardInstructorDay: getRequiredElement<HTMLElement>("#riskCardInstructorDay"),
  riskInstructorDayConflict: getRequiredElement<HTMLElement>("#riskInstructorDayConflict"),
  riskCardFoDay: getRequiredElement<HTMLElement>("#riskCardFoDay"),
  riskFoDayConflict: getRequiredElement<HTMLElement>("#riskFoDayConflict"),
  riskCardHrd: getRequiredElement<HTMLElement>("#riskCardHrd"),
  riskHrdValidation: getRequiredElement<HTMLElement>("#riskHrdValidation"),
  riskCardHoliday: getRequiredElement<HTMLElement>("#riskCardHoliday"),
  riskHolidayApplied: getRequiredElement<HTMLElement>("#riskHolidayApplied"),

  cohortSelect: getRequiredElement<HTMLSelectElement>("#cohort"),
  cohortInfo: getRequiredElement<HTMLElement>("#cohortInfo"),
  downloadButton: getRequiredElement<HTMLButtonElement>("#download"),
  hrdValidationPanel: getRequiredElement<HTMLElement>("#hrdValidationPanel"),
  hrdValidationList: getRequiredElement<HTMLUListElement>("#hrdValidationList"),

  timelineRange: getRequiredElement<HTMLElement>("#timelineRange"),
  timelineEmpty: getRequiredElement<HTMLElement>("#timelineEmpty"),
  timelineViewTypeSelect: getRequiredElement<HTMLSelectElement>("#timelineViewTypeSelect"),
  assigneeTimelineControls: getRequiredElement<HTMLElement>("#assigneeTimelineControls"),
  assigneeModeInstructorButton: getRequiredElement<HTMLButtonElement>("#assigneeModeInstructor"),
  assigneeModeStaffButton: getRequiredElement<HTMLButtonElement>("#assigneeModeStaff"),
  weekGridControls: getRequiredElement<HTMLElement>("#weekGridControls"),
  weekPrevButton: getRequiredElement<HTMLButtonElement>("#weekPrevButton"),
  weekNextButton: getRequiredElement<HTMLButtonElement>("#weekNextButton"),
  weekLabel: getRequiredElement<HTMLElement>("#weekLabel"),
  monthCalendarControls: getRequiredElement<HTMLElement>("#monthCalendarControls"),
  monthPrevButton: getRequiredElement<HTMLButtonElement>("#monthPrevButton"),
  monthNextButton: getRequiredElement<HTMLButtonElement>("#monthNextButton"),
  monthLabel: getRequiredElement<HTMLElement>("#monthLabel"),
  timelineDetailPanel: getRequiredElement<HTMLElement>("#timelineDetailPanel"),
  timelineList: getRequiredElement<HTMLElement>("#timelineList"),
  notificationStatusList: getRequiredElement<HTMLElement>("#notificationStatusList"),

  scheduleCohortInput: getRequiredElement<HTMLInputElement>("#scheduleCohort"),
  scheduleStartDateInput: getRequiredElement<HTMLInputElement>("#scheduleStartDate"),
  scheduleTotalHoursInput: getRequiredElement<HTMLInputElement>("#scheduleTotalHours"),
  dayTemplateTable: getRequiredElement<HTMLTableElement>("#dayTemplateTable"),
  scheduleTemplateSelect: getRequiredElement<HTMLSelectElement>("#scheduleTemplateSelect"),
  scheduleTemplateNameInput: getRequiredElement<HTMLInputElement>("#scheduleTemplateName"),
  loadScheduleTemplateButton: getRequiredElement<HTMLButtonElement>("#loadScheduleTemplateButton"),
  saveScheduleTemplateButton: getRequiredElement<HTMLButtonElement>("#saveScheduleTemplateButton"),
  deleteScheduleTemplateButton: getRequiredElement<HTMLButtonElement>("#deleteScheduleTemplateButton"),
  scheduleTemplateStatus: getRequiredElement<HTMLElement>("#scheduleTemplateStatus"),

  holidayDateInput: getRequiredElement<HTMLInputElement>("#holidayDateInput"),
  addHolidayButton: getRequiredElement<HTMLButtonElement>("#addHolidayButton"),
  loadPublicHolidaysButton: getRequiredElement<HTMLButtonElement>("#loadPublicHolidaysButton"),
  clearHolidaysButton: getRequiredElement<HTMLButtonElement>("#clearHolidaysButton"),
  dedupeHolidaysButton: getRequiredElement<HTMLButtonElement>("#dedupeHolidaysButton"),
  holidayLoadStatus: getRequiredElement<HTMLElement>("#holidayLoadStatus"),
  holidayLoadSpinner: getRequiredElement<HTMLElement>("#holidayLoadSpinner"),
  holidayList: getRequiredElement<HTMLUListElement>("#holidayList"),

  customBreakDateInput: getRequiredElement<HTMLInputElement>("#customBreakDateInput"),
  addCustomBreakButton: getRequiredElement<HTMLButtonElement>("#addCustomBreakButton"),
  customBreakList: getRequiredElement<HTMLUListElement>("#customBreakList"),

  scheduleInstructorCodeInput: getRequiredElement<HTMLInputElement>("#scheduleInstructorCode"),
  scheduleClassroomCodeInput: getRequiredElement<HTMLInputElement>("#scheduleClassroomCode"),
  scheduleSubjectCodeInput: getRequiredElement<HTMLInputElement>("#scheduleSubjectCode"),

  generateScheduleButton: getRequiredElement<HTMLButtonElement>("#generateScheduleButton"),
  pushScheduleToConflicts: getRequiredElement<HTMLInputElement>("#pushScheduleToConflicts"),
  appendScheduleButton: getRequiredElement<HTMLButtonElement>("#appendScheduleButton"),

  scheduleError: getRequiredElement<HTMLElement>("#scheduleError"),
  scheduleResult: getRequiredElement<HTMLElement>("#scheduleResult"),
  scheduleSummary: getRequiredElement<HTMLElement>("#scheduleSummary"),
  scheduleSkippedSummary: getRequiredElement<HTMLElement>("#scheduleSkippedSummary"),
  scheduleSkippedDetails: getRequiredElement<HTMLElement>("#scheduleSkippedDetails"),
  scheduleDaysInfo: getRequiredElement<HTMLElement>("#scheduleDaysInfo"),
  scheduleDaysPreview: getRequiredElement<HTMLUListElement>("#scheduleDaysPreview"),
  scheduleAppendStatus: getRequiredElement<HTMLElement>("#scheduleAppendStatus"),

  staffingStatus: getRequiredElement<HTMLElement>("#staffingStatus"),
  staffingModeSelect: getRequiredElement<HTMLSelectElement>("#staffingModeSelect"),
  staffingModeHint: getRequiredElement<HTMLElement>("#staffingModeHint"),
  staffP1WeeksInput: getRequiredElement<HTMLInputElement>("#staffP1Weeks"),
  staff365WeeksInput: getRequiredElement<HTMLInputElement>("#staff365Weeks"),
  staffAutoFillButton: getRequiredElement<HTMLButtonElement>("#staffAutoFill"),
  staffRefreshButton: getRequiredElement<HTMLButtonElement>("#staffRefresh"),
  staffExportCsvButton: getRequiredElement<HTMLButtonElement>("#staffExportCsv"),
  staffExportModeSelect: getRequiredElement<HTMLSelectElement>("#staffExportMode"),
  staffExportIncludeDetails: getRequiredElement<HTMLInputElement>("#staffExportIncludeDetails"),
  staffExportModeHint: getRequiredElement<HTMLElement>("#staffExportModeHint"),
  staffExportWarningsAgree: getRequiredElement<HTMLInputElement>("#staffExportWarningsAgree"),
  staffExportValidationPanel: getRequiredElement<HTMLElement>("#staffExportValidationPanel"),
  staffExportValidationList: getRequiredElement<HTMLUListElement>("#staffExportValidationList"),
  staffModuleManagerContainer: getRequiredElement<HTMLElement>("#staffModuleManagerContainer"),
  staffModuleManagerContainerAdmin: getRequiredElement<HTMLElement>("#staffModuleManagerContainerAdmin"),
  staffAdvancedContainer: getRequiredElement<HTMLElement>("#staffAdvancedContainer"),
  staffMatrixContainer: getRequiredElement<HTMLElement>("#staffMatrixContainer"),
  staffCohortGantt: getRequiredElement<HTMLElement>("#staffCohortGantt"),
  staffAssigneeGantt: getRequiredElement<HTMLElement>("#staffAssigneeGantt"),
  staffKpiBody: getRequiredElement<HTMLTableSectionElement>("#staffKpiBody"),
  staffDetailContainer: getRequiredElement<HTMLElement>("#staffDetailContainer"),

  errorCount: getRequiredElement<HTMLElement>("#errorCount"),
  errorList: getRequiredElement<HTMLUListElement>("#errorList"),
  errorEmpty: getRequiredElement<HTMLElement>("#errorEmpty"),

  confCount: getRequiredElement<HTMLElement>("#confCount"),
  confTableBody: getRequiredElement<HTMLTableSectionElement>("#confTable tbody"),
  computeConflictsButton: getRequiredElement<HTMLButtonElement>("#computeConflicts"),
  keySearchInput: getRequiredElement<HTMLInputElement>("#keySearch"),
  downloadTimeConflictsButton: getRequiredElement<HTMLButtonElement>("#downloadTimeConflicts"),
  confRenderNotice: getRequiredElement<HTMLElement>("#confRenderNotice"),

  tabTimeConflicts: getRequiredElement<HTMLButtonElement>("#tabTimeConflicts"),
  tabInstructorDayConflicts: getRequiredElement<HTMLButtonElement>("#tabInstructorDayConflicts"),
  tabFoDayConflicts: getRequiredElement<HTMLButtonElement>("#tabFoDayConflicts"),
  timeConflictPanel: getRequiredElement<HTMLElement>("#timeConflictPanel"),
  instructorDayConflictPanel: getRequiredElement<HTMLElement>("#instructorDayConflictPanel"),
  foDayConflictPanel: getRequiredElement<HTMLElement>("#foDayConflictPanel"),
  instructorDaySearchInput: getRequiredElement<HTMLInputElement>("#instructorDaySearch"),
  foDaySearchInput: getRequiredElement<HTMLInputElement>("#foDaySearch"),
  downloadInstructorDayConflictsButton: getRequiredElement<HTMLButtonElement>("#downloadInstructorDayConflicts"),
  downloadFoDayConflictsButton: getRequiredElement<HTMLButtonElement>("#downloadFoDayConflicts"),
  instructorDayOverlapCount: getRequiredElement<HTMLElement>("#instructorDayOverlapCount"),
  instructorDayOverlapBody: getRequiredElement<HTMLTableSectionElement>("#instructorDayOverlapBody"),
  instructorDayRenderNotice: getRequiredElement<HTMLElement>("#instructorDayRenderNotice"),
  foOverlapCount: getRequiredElement<HTMLElement>("#foOverlapCount"),
  foOverlapBody: getRequiredElement<HTMLTableSectionElement>("#foOverlapBody"),
  foDayRenderNotice: getRequiredElement<HTMLElement>("#foDayRenderNotice"),

  saveProjectButton: getRequiredElement<HTMLButtonElement>("#saveProjectButton"),
  loadProjectButton: getRequiredElement<HTMLButtonElement>("#loadProjectButton"),
  resetProjectButton: getRequiredElement<HTMLButtonElement>("#resetProjectButton"),
  printReportButton: getRequiredElement<HTMLButtonElement>("#printReportButton"),
  loadProjectInput: getRequiredElement<HTMLInputElement>("#loadProjectInput"),
  stateStorageStatus: getRequiredElement<HTMLElement>("#stateStorageStatus"),
  stateStorageWarning: getRequiredElement<HTMLElement>("#stateStorageWarning"),

  demoSampleSection: getRequiredElement<HTMLElement>("#demoSampleSection"),
  demoSampleSelect: getRequiredElement<HTMLSelectElement>("#demoSampleSelect"),
  loadDemoSampleButton: getRequiredElement<HTMLButtonElement>("#loadDemoSampleButton"),
  restorePreviousStateButton: getRequiredElement<HTMLButtonElement>("#restorePreviousStateButton"),
  demoSampleBanner: getRequiredElement<HTMLElement>("#demoSampleBanner"),

  opsChecklistList: getRequiredElement<HTMLUListElement>("#opsChecklistList"),

  printReportCard: getRequiredElement<HTMLElement>("#printReportCard"),
  printReportMeta: getRequiredElement<HTMLElement>("#printReportMeta"),
  printCohortGantt: getRequiredElement<HTMLElement>("#printCohortGantt"),
  printAssigneeGantt: getRequiredElement<HTMLElement>("#printAssigneeGantt"),
  printKpiContainer: getRequiredElement<HTMLElement>("#printKpiContainer"),
  printConflictTitle: getRequiredElement<HTMLElement>("#printConflictTitle"),
  printConflictContainer: getRequiredElement<HTMLElement>("#printConflictContainer"),

  instructorCodeInput: getRequiredElement<HTMLInputElement>("#instructorCodeInput"),
  instructorNameInput: getRequiredElement<HTMLInputElement>("#instructorNameInput"),
  instructorMemoInput: getRequiredElement<HTMLInputElement>("#instructorMemoInput"),
  upsertInstructorButton: getRequiredElement<HTMLButtonElement>("#upsertInstructorButton"),
  instructorDirectoryBody: getRequiredElement<HTMLTableSectionElement>("#instructorDirectoryBody"),
  courseIdInput: getRequiredElement<HTMLInputElement>("#courseIdInput"),
  courseNameInput: getRequiredElement<HTMLInputElement>("#courseNameInput"),
  courseMemoInput: getRequiredElement<HTMLInputElement>("#courseMemoInput"),
  upsertCourseButton: getRequiredElement<HTMLButtonElement>("#upsertCourseButton"),
  courseRegistryBody: getRequiredElement<HTMLTableSectionElement>("#courseRegistryBody"),
  subjectCourseSelect: getRequiredElement<HTMLSelectElement>("#subjectCourseSelect"),
  mappingCourseSelect: getRequiredElement<HTMLSelectElement>("#mappingCourseSelect"),
  courseTemplateCourseSelect: getRequiredElement<HTMLSelectElement>("#courseTemplateCourseSelect"),
  courseTemplateNameInput: getRequiredElement<HTMLInputElement>("#courseTemplateNameInput"),
  courseTemplateSelect: getRequiredElement<HTMLSelectElement>("#courseTemplateSelect"),
  saveCourseTemplateButton: getRequiredElement<HTMLButtonElement>("#saveCourseTemplateButton"),
  loadCourseTemplateButton: getRequiredElement<HTMLButtonElement>("#loadCourseTemplateButton"),
  deleteCourseTemplateButton: getRequiredElement<HTMLButtonElement>("#deleteCourseTemplateButton"),
  courseTemplateStatus: getRequiredElement<HTMLElement>("#courseTemplateStatus"),
  subjectCodeInput: getRequiredElement<HTMLInputElement>("#subjectCodeInput"),
  subjectNameInput: getRequiredElement<HTMLInputElement>("#subjectNameInput"),
  subjectMemoInput: getRequiredElement<HTMLInputElement>("#subjectMemoInput"),
  upsertSubjectButton: getRequiredElement<HTMLButtonElement>("#upsertSubjectButton"),
  subjectDirectoryBody: getRequiredElement<HTMLTableSectionElement>("#subjectDirectoryBody"),
  applySubjectMappingsButton: getRequiredElement<HTMLButtonElement>("#applySubjectMappingsButton"),
  subjectMappingContainer: getRequiredElement<HTMLElement>("#subjectMappingContainer"),
  instructorTabCourse: getRequiredElement<HTMLButtonElement>("#instructorTabCourse"),
  instructorTabRegister: getRequiredElement<HTMLButtonElement>("#instructorTabRegister"),
  instructorTabMapping: getRequiredElement<HTMLButtonElement>("#instructorTabMapping"),
  instructorTabSubject: getRequiredElement<HTMLButtonElement>("#instructorTabSubject"),
  instructorCoursePanel: getRequiredElement<HTMLElement>("#instructorCoursePanel"),
  instructorRegisterPanel: getRequiredElement<HTMLElement>("#instructorRegisterPanel"),
  instructorMappingPanel: getRequiredElement<HTMLElement>("#instructorMappingPanel"),
  instructorSubjectPanel: getRequiredElement<HTMLElement>("#instructorSubjectPanel"),
};
